//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMA_FAQ
    {
        public decimal ID { get; set; }
        public string QUESTION { get; set; }
        public System.DateTime CREATEDAT { get; set; }
        public System.DateTime MODIFIEDAT { get; set; }
        public string ANSWER { get; set; }
        public string ISDELETED { get; set; }
        public string ISARCHIVED { get; set; }
    }
}
