//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAAPI.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMAAUTHOR
    {
        public decimal ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string FULLNAME { get; set; }
    }
}
