//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMAAPI.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimaEntities : DbContext
    {
        public SimaEntities()
            : base("name=SimaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SIMA_NEWS> SIMA_NEWS { get; set; }
        public DbSet<SIMA_FAQ> SIMA_FAQ { get; set; }
        public DbSet<SIMAAUTHOR> SIMAAUTHORS { get; set; }
    }
}
